
project_id = "hgdcneupkjiidjahpszh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
enabled = false
connection_string = "connection_string"
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "https://api.supabase.com"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
port = 54325

[analytics]
enabled = false
port = 54327

[experimental.functions]
enabled = true
port = 54328

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true
