// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgdcneupkjiidjahpszh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnZGNuZXVwa2ppaWRqYWhwc3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjI1MTksImV4cCI6MjA2MTQ5ODUxOX0.ijoJrBxGYNFimhXLqNe-eygKoZfvvRmIPZY8UV0C76o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);